### ISSUE TITLE
trouble with get_processing_program interface function

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/ispyb-api#169]
I have a class with something along the lines of:

```
self.conn = ispyb.open(self.conf_file)
appid = 56988036
pp = self.conn.get_processing_program(appid)
```
or
```
self.conn = ispyb.open(self.conf_file)
appid = 56988036
status = self.conn.get_processing_program(appid).status_text
```

and it gives me this error:

AutoProcProgram #56988034 (not yet loaded from database)

Is the `get_processing_program` function expected to work? I have had success with the `get_data_collection` function, but haven't thoroughly explored the other functions in `/ispyb-api/src/ispyb/model/interface.py`

**Comment by rjgildea** [comment]
`ispyb.model` has been [deprecated since 6.0.0](https://github.com/DiamondLightSource/ispyb-api/blob/master/HISTORY.rst#600-2021-03-05) as it has been superceded by the `ispyb.sqlalchemy` interface that was introduced at the same time (see also #123). This interface is much more flexible and powerful than the previous `ispyb.model` (which should probably be removed entirely at some point to avoid further confusion). Please let us know if you have any issues or questions about using the `isbpy.sqlalchemy` interface.

**Comment by dsclassen** [comment]
This is good to know. I guess I should pay more attention to the release notes.

How do I use SQLAlchemy? Are there any example code snippets available?

**Comment by dsclassen** [comment]
It would really help my efforts to use the ISPyB database if I knew how to use this new fangled `ispyb.sqlalchemy` interface.
Thanks.

**Comment by dsclassen** [comment]
Well I found `job.py` and `last_data_collections_on.py` which has given me a little bit of a clue as to how I should proceed.

I guess I need to take a crash course on SQL syntax...

**Comment by rjgildea** [comment]
Thanks for the reminder that I'd started, but not finished, working on integrating an `ispyb.sqlalchemy` tutorial into the documentation. I've now got it into a state where it's hopefully at least better than the existing lack of documentation. I'd welcome your thoughts on the open PR https://github.com/DiamondLightSource/ispyb-api/pull/172.
