### ISSUE TITLE
Is there an updated pipeline2ispyb.py script？

### ISSUE THREAD

**Issue by Baokangwen** [DiamondLightSource/ispyb-api#221]
@tschoonj @ndevenish @kevinpetersavage @isikhar @graeme-winter 
Dear everyone
Have the latest pipeline2ispyb.py scripts? It feels like the old script is not very complete.

Best regards,
keven

**Comment by KarlLevik** [comment]
Hi Keven,

Afraid not.

The script was written 10 years ago, and has not been updated much since.

This was also before sqlalchemy was included in the project, so if you're looking for sqlalchemy examples, then it's best to look elsewhere, perhaps [here](https://github.com/DiamondLightSource/ispyb-api/blob/main/docs/sqlalchemy.rst).

**Comment by Baokangwen** [comment]
@KarlLevik 
Thank you
