### ISSUE TITLE
ISPyB API version 5 release

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/ispyb-api#59]
Target date 15th of January 2019

**Comment by Anthchirp** [comment]
TBD:
* [ ] make changelog
* [x] make release

**Comment by KarlLevik** [comment]
Draft proposal for changelog since v4.13.2 (13. Nov. 2018):

* Configurable reconnection parameters (`reconn_attempts` and `reconn_delay`)
* New methods for: 
  * storing x-ray centring results 
  * retrieving persons on a session
  * un-assigning all containers on a certain beamline
* `update_container_assign` now returns the `containerId` and the new `containerStatus`
* Authorisation built into the queries for relevant stored procedures  
* Exceptions improved
* Use the `testdb` fixture for most test
* Removed:
  * mxprocessing: `upsert_program` replaced with `upsert_program_ex` (TODO!)
  * processing interface: removed `get_processing_job`

**Comment by KarlLevik** [comment]
Added changelog here: https://github.com/DiamondLightSource/ispyb-api/releases/tag/v5.0.0

Should it exist as a file in the repo as well?

**Comment by Anthchirp** [comment]
Yes, I think it should go into the repository as well. I've put in a pull request -> #70 
If everything works correctly this should be picked up by the documentation build, too.
