### ISSUE TITLE
mysql-connector dependency

### ISSUE THREAD

**Issue by tschoonj** [DiamondLightSource/ispyb-api#84]
@jacobfilik @Anthchirp @KarlLevik 

https://github.com/DiamondLightSource/ispyb-api/blob/752a0d7152513fe0d879e8d09172d016a0860ee5/setup.py#L18

The `mysql-connector<2.2.3` dependency is rather problematic, and is in fact ignored when using conda to install ispyb (see my ticket [here](https://github.com/conda-forge/ispyb-feedstock/issues/22), which pulls in the latest version of `mysql-connector-python` anyway.

This results in more problems when running zocalo, because setuptools keeps looking for `mysql-connector`, and it doesn't consider `mysql-connector` and `mysql-connector-python` to be the same packages (they are in fact different PyPI projects, with the former deprecated in favor of the latter...), so even `conda install -c conda-forge mysql-connector-python=2.2.2` will not help here.

To fix the zocalo error I ended up creating a custom build of `mysql-connector-python` with a patch applied to its setup.py to ensure it would be recognized by pip and setuptools as `mysql-connector`. 

I think the dependency in ispyb's setup.py should be changed from `mysql-connector` to `mysql-connector-python`, and the version constraint should be dropped as one shouldn't depend on a specific version of a package that is [+2 years old](https://github.com/mysql/mysql-connector-python/releases?after=8.0.5).

**Comment by KarlLevik** [comment]
If I remember correctly, I think the reason for the restriction was that Markus wanted a pure Python package due to restrictions with the build system used by Zocalo for MX. 

MariaDB has been working on their [own Python connector](https://github.com/MariaDB/mariadb-connector-python), but this project appears to have stalled, and it looks like it's not going to be pure Python anyway. MariaDB Support has told me their connector won't see a GA release until next year.

So therefore I think we just have to accept that we can't get a pure Python connector, and Markus will have to figure out a way for their build system to cope with this.

**Comment by Anthchirp** [comment]
fixed by #86
